routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');
Route::get('animals/checked-out', 'AnimalController@showCheckedOutAnimals');
Route::get('animals/{id}/checkout', 'AnimalController@showCheckoutPage');
Route::post('animals/{id}/checkout', 'AnimalController@checkoutAnimal')->name('animals.checkout');
Route::get('animals/{id}/check-in', 'AnimalController@showCheckinPage');
Route::post('animals/{id}/check-in', 'AnimalController@checkinAnimal')->name('animals.checkin');
Route::resource('animals', 'AnimalController');
Route::get('/animal/{id}', 'AnimalController@show');
Route::get('/animal/{id}/add-note', 'AnimalController@showAddAnimalNotePage');
Route::post('/animal/{id}/add-note', 'AnimalController@addAnimalNote')->name('animals.add-note');


Route::get('admin/settings', 'AdminController@showSettings');
Route::post('admin/settings/visit-type/add', 'AdminController@addVisitType')->name('admin.add_type');

Route::get('admin/visit-types', 'AdminController@showVisitTypes');

Route::get('admin/certifications', 'AdminController@showHandlingCertificationSettings');
Route::post('admin/certifications', 'AdminController@addHandlingCertifications')->name('admin.certifications');
Route::get('admin/employees', 'AdminController@showEmployeeList');
Route::post('admin/employee/{id}/renew', 'AdminController@renewCertification');
Route::delete('admin/employee/{id}', 'AdminController@deleteCertification');
Route::delete('admin/animal/{id}', 'AdminController@deleteAnimal');
Route::get('admin/employee/{id}', 'AdminController@showEmployee')->name('admin.employee');
Route::get('admin/access-code', 'AdminController@showAccessCodeForm');
Route::post('admin/access-code', 'AdminController@changeAccessCode')->name('admin.access-code');
Route::post('admin/employee/{id}/role', 'AdminController@changeEmployeeRole')->name('admin.employee-role');
Route::get('admin/categories', 'AdminController@showAnimalCategories');
Route::post('admin/categories', 'AdminController@createAnimalCategory')->name('admin.categories');
Route::patch('admin/categories/{id}', 'AdminController@editAnimalCategory');
Route::delete('admin/categories/{id}', 'AdminController@deleteAnimalCategory');
Route::get('admin/species', 'AdminController@showAnimalSpecies');
Route::post('admin/species', 'AdminController@createAnimalSpecie')->name('admin.species');
Route::patch('admin/species/{id}', 'AdminController@editAnimalSpecies');
Route::delete('admin/species/{id}', 'AdminController@deleteAnimalSpecies');

app/Animal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Storage;
use App\AnimalSpecie;

class Animal extends Model
{
    protected $fillable = ['name', 'nickname', 'animal_species_id', 'flagged', 'image', 'bio'];

    protected $hidden = ['image'];

    protected $appends = ['image_url', 'animal_specie'];

    public function getImageUrlAttribute()
    {
        $filesystem_driver = env('FILESYSTEM_DRIVER', 'local');
        if ($filesystem_driver === 'ftp') {
            return env('SERVER_URL').'/'.str_replace('storage/', 'public/', $this->image);
        }
        else {
            return asset($this->image);
        }
    }

    public function getAnimalSpecieAttribute()
    {
        return AnimalSpecie::find($this->animal_species_id);
    }
}

app/Http/Controllers/AnimalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Animal;
use App\AnimalNote;
use App\User;
use App\AnimalCheckout;
use App\AnimalCategory;
use App\AnimalSpecie;
use App\VisitType;
use Carbon\Carbon;
use Auth;

class AnimalController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $animal_checkouts = AnimalCheckout::where('checked_in_at', null)->get()->toArray();
        $categories = AnimalCategory::all();
        $species = AnimalSpecie::all();
        $animals = Animal::all()->toArray();

        foreach ($animal_checkouts as $animal_checkout) {
            foreach ($animals as $index => $animal) {
                if ($animal['id'] == $animal_checkout['animal_id']) {
                    $animals[$index]['disabled'] = true;
                }
            }
        }

        $data = [
            'categories' => json_encode($categories),
            'animals' => json_encode($animals),
            'species' => $species
        ];

        return view('animals.list')->with($data);
    }

    public function showCheckedOutAnimals()
    {
        $animal_checkouts = AnimalCheckout::where('checked_in_at', null)->get();
        $all_animal_checkouts = AnimalCheckout::orderBy('checked_in_at', 'desc')->get();

        $data = [
            'animal_checkouts' => $animal_checkouts,
            'all_animal_checkouts' => $all_animal_checkouts
        ];

        return view('animals.checkedout')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = AnimalCategory::all();
        $species = AnimalSpecie::all();

        $data = [
            'categories' => $categories,
            'species' => $species
        ];

        return view('animals.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image_path = $request->file('image')->store('public');
        $image_path = str_replace('public/', 'storage/', $image_path);

        $animal = Animal::create([
            'name' => $request->input('name'),
            'nickname' => $request->input('nickname'),
            'animal_species_id' => $request->input('species'),
            'flagged' => false,
            'image' => $image_path,
            'bio' => $request->input('bio')
        ]);

        return redirect('animals');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $animal = Animal::find($id);
        $animalNotes = AnimalNote::where('animal_id',$id)
                                ->orderBy('created_at', 'desc')
                                ->get();
        return view('animals.dashboard')->with(
            ['animal' => $animal])->with(
            ['animalNotes' => $animalNotes]);
    }

    public function showCheckoutPage($id)
    {
        $animal = Animal::find($id);
        $animal_checkouts = AnimalCheckout::where('animal_id', $id)->where('checked_in_at', '>=', Carbon::yesterday())->get();
        $user = Auth::user();
        $visit_types = VisitType::all();
        $time = Carbon::now('America/Denver');
        $can_check_out = $this->canCheckOut($animal_checkouts);

        $data = [
            'animal' => $animal,
            'can_check_out' => $can_check_out,
            'user' => $user,
            'visit_types' => $visit_types,
            'time' => $time
        ];

        return view('animals.checkout')->with($data);
    }

    public function checkoutAnimal(Request $request, $id)
    {
        $animal = Animal::find($id);
        $user_id = $request->input('checked_out_by');
        $visit_type_id = $request->input('visit_purpose');
        $time = Carbon::now('America/Denver');

        $animal_checkout = AnimalCheckout::create([
            'animal_id' => $animal->id,
            'user_id' => $user_id,
            'visit_type_id' => $visit_type_id,
            'checked_out_at' => $time
        ]);

        return redirect('animals/checked-out');
    }

    public function showCheckinPage(Request $request, $id)
    {
        $animal_checkout = AnimalCheckout::find($id);
        $checked_out_user = User::find($animal_checkout->user_id);
        $animal = Animal::find($animal_checkout->animal_id);
        $user = Auth::user();
        $time = Carbon::now('America/Denver');

        $data = [
            'animal_checkout' => $animal_checkout,
            'animal' => $animal,
            'user' => $user,
            'time' => $time,
            'checked_out_user' => $checked_out_user
        ];

        return view('animals.checkin')->with($data);
    }

    public function checkinAnimal(Request $request, $id)
    {
        $animal_checkout = AnimalCheckout::find($id);
        $note = $request->input('note');
        $times_handled = $request->input('times_handled');
        $time = Carbon::now('America/Denver');

        if (!is_null($note)) {
            $animal_note = AnimalNote::create([
                'animal_id' => $animal_checkout->animal_id,
                'note' => $note
            ]);
        }

        $animal_checkout->update([
            'checked_in_at' => $time,
            'times_handled' => $times_handled
        ]);

        return redirect('animals');
    }

    public function showAddAnimalNotePage($id) {
        $animal = Animal::find($id);

        $data = [
            'animal' => $animal,
        ];

        return view('animals.add-note')->with($data);
    }

    public function addAnimalNote(Request $request, $id) {
        $note = $request->input('note');

        if (!is_null($note)) {
            $animal_note = AnimalNote::create([
                'animal_id' => $id,
                'note' => $note
            ]);
        }
        return redirect('animal/'.$id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $animal = Animal::find($id);
        $categories = AnimalCategory::all();
        $species = AnimalSpecie::all();

        $data = [
            'animal' => $animal,
            'categories' => $categories,
            'species' => $species
        ];

        return view('animals.edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $animal = Animal::find($id);
        if (!is_null($request->file('image'))) {
            $image_path = $request->file('image')->store('public');
            $image_path = str_replace('public/', 'storage/', $image_path);
            $animal->update([
                'image' => $image_path
            ]);
        }

        $animal->update([
            'name' => $request->input('name'),
            'nickname' => $request->input('nickname'),
            'animal_species_id' => $request->input('species'),
            'flagged' => false,
            'bio' => $request->input('bio')
        ]);

        return redirect('animal/'.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    private function canCheckOut($animal_checkouts){
        $can_check_out = true;

        $times_handled = 0;
        if (count($animal_checkouts) > 0) {
            $checked_out_yesterday = Carbon::parse($animal_checkouts->last()->checked_in_at)->isYesterday();
            foreach ($animal_checkouts as $animal_checkout) {
                $times_handled += $animal_checkout->times_handled;
            }

            if ($checked_out_yesterday || $times_handled >= 5) {
                $can_check_out = false;
            }
        }

        return $can_check_out;
    }
}

resources/views/animals/add-note.blade.php
@extends('layouts.default')

@section('content')
<div class="segment ui">
    <h2 class="ui horizontal divider header">
        Add a  Note
    </h2>
    <div class="content">
        <form class="ui form" method="POST" action="{{ route('animals.add-note', $animal->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="field">
                <label for="note">Note</label>
                <textarea id="note" name="note"></textarea>
            </div>

            <button type="submit" class="ui orange button">Add Note</button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
    window.$('.ui.dropdown').dropdown();
</script>
@endsection

resources/views/animals/checkedout.blade.php
@extends('layouts.default')

@section('content')
    <checked-out :animals="{{$animal_checkouts}}" :history="false"></checked-out>
    <br><br><br>
    <checked-out :animals="{{$all_animal_checkouts}}" :history="true"></checked-out>
@endsection

resources/views/animals/checkin.blade.php
@extends('layouts.default')

@section('content')
    <div class="content">
        <form class="ui form" method="POST" action="{{ route('animals.checkin', $animal_checkout->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="field">
                <label>Animal</label>
                <p>{{$animal->name}} ({{$animal->nickname}})</p>
            </div>

            <div class="field">
                <label>Checked Out By</label>
                <p>{{$checked_out_user->name}}</p>
            </div>

            <div class="field">
                <label>Checked Out</label>
                <p>{{$animal_checkout->checked_out_at_readable}}</p>
            </div>

            <div class="field">
                <label for="checked_out_by">Check in by</label>
                <input type="text" class="ui dropdown" disabled value="{{$user->name}}">
                <input type="hidden" id="checked_in_by" name="checked_in_by" value="{{$user->id}}">
            </div>

            <div class="field">
                <label for="checkin_time">Time of Check-in</label>
                <div class="ui input left icon">
                    <i class="time icon"></i>
                    <input id="checkin_time" type="text" name="checkin_time" value="{{$time}}" disabled>
                </div>
            </div>

            <div class="field">
                <label for="times_handled">Times Handled</label>
                <div class="ui input">
                    <input id="times_handled" type="number" name="times_handled">
                </div>
            </div>

            <div class="field">
                <label for="note">Note</label>
                <textarea id="note" name="note"></textarea>
            </div>

            <button type="submit" class="ui orange button">Check In {{$animal->name}}</button>
        </form>
    </div>
@endsection

@section('scripts')
@parent
<script>
    window.$('.ui.dropdown').dropdown();
</script>
@endsection

resources/views/animals/checkout.blade.php
@extends('layouts.default')

@section('content')
    <div class="ui segment">
    <div class="ui header">Checkout {{$animal->name}}</div>

    <div class="content">
        <form class="ui form" method="POST" action="{{ route('animals.checkout', $animal->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="field">
                <label for="checked_out_by">Check out by</label>
                <input type="text" class="ui dropdown" disabled value="{{$user->name}}">
                <input type="hidden" id="checked_out_by" name="checked_out_by" value="{{$user->id}}">
            </div>

            <div class="field">
                <label for="visit_purpose">Purpose of Visit</label>
                <select class="ui dropdown" id="visit_purpose" name="visit_purpose" required>
                    @foreach ($visit_types as $visit_type)
                    <option value="{{$visit_type->id}}">{{$visit_type->title}}</option>
                    @endforeach
                </select>
            </div>

            <div class="field">
                <label for="checkout_time">Time of Checkout</label>
                <div class="ui input left icon">
                    <i class="time icon"></i>
                    <input id="checkout_time" type="text" name="checkout_time" value="{{$time}}" disabled>
                </div>
            </div>

            @if ($can_check_out)
                <button style="display:block;" type="submit" class="ui orange button">Checkout Animal</button>
            @else
                <div style="display:block;" class="ui disabled orange button">Checkout Animal</div>
                <div class="ui pointing label">
                    Animal was checked out <br> <br> or was handled too many times.
                </div>
            @endif
        </form>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
    window.$('.ui.dropdown').dropdown();
</script>
@endsection

resources/views/animals/create.blade.php
@extends('layouts.default')

@section('content')

<div class="ui segment">
    <div class="ui header">Add Animal</div>
    <div class="content">
        <form class="ui form" method="POST" action="{{ route('animals.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="field">
                <label for="name">Name</label>
                <input id="name" type="text" name="name" required autofocus>
            </div>

            <div class="field">
                <label for="nickname">Nickname</label>
                <input id="nickname" type="text" name="nickname" required>
            </div>

            <div class="field">
                    <label for="species">Species</label>
                    <select class="ui dropdown" id="species" name="species" required>
                        @foreach($species as $specie)
                            <option value="{{$specie->id}}">{{$specie->name}}</option>
                        @endforeach
                    </select>
                </div>

            <div class="field">
                <label for="image">Image</label>
                <input id="image" type="file" name="image" required>
            </div>

            <div class="field">
                <label for="bio">Animal Bio</label>
                <textarea id="bio" name="bio"></textarea>
            </div>

            <button type="submit" class="ui orange button">Add Animal</button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
    window.$('.ui.dropdown').dropdown();
</script>
@endsection

resources/views/animals/dashboard.blade.php
@extends('layouts.default')

@section('content')
    <animal-dashboard :animal="{{$animal}}" :animal-notes="{{$animalNotes}}"></animal-dashboard>
@endsection 

resources/views/animals/edit.blade.php
@extends('layouts.default')

@section('content')

<div class="ui segment">
    <div class="ui header">Add Animal</div>
    <div class="content">
        <form class="ui form" method="POST" action="{{ route('animals.update', ['id' => $animal->id]) }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            {!! method_field('patch') !!}

            <div class="field">
                <label for="name">Name</label>
                <input id="name" type="text" name="name" value="{{$animal->name}}" required autofocus>
            </div>

            <div class="field">
                <label for="nickname">Nickname</label>
                <input id="nickname" type="text" name="nickname" value="{{$animal->nickname}}" required>
            </div>

            <div class="field">
                    <label for="animal_species_id">Species</label>
                    <select class="ui dropdown" id="species" name="species" required>
                        @foreach($species as $specie)
                        @if ($specie->id == $animal->animal_species_id)
                            <option value="{{$specie->id}}" selected>{{$specie->name}}</option>
                        @else
                            <option value="{{$specie->id}}">{{$specie->name}}</option>
                        @endif
                        @endforeach
                    </select>
                </div>

            <img src="{{$animal->image_url}}" />
            <div class="field">
                <label for="image">Image</label>
                <input id="image" type="file" name="image" value="{{$animal->image}}">
            </div>

            <div class="field">
                <label for="bio">Animal Bio</label>
                <textarea id="bio" name="bio">{{$animal->bio}}</textarea>
            </div>

            <button type="submit" class="ui orange button">Update Animal</button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
    window.$('.ui.dropdown').dropdown();
</script>
@endsection

resources/views/animals/list.blade.php
@extends('layouts.default')
@section('content')
    <search 
    :animals="{{$animals}}" 
    :categories="{{$categories}}" 
    :species="{{$species}}"
    :user="{{Auth::user()}}"></search>
@endsection